name: Build Book PDF

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build PDF with Asciidoctor
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: false

      - name: Install Asciidoctor PDF toolchain
        run: |
          gem install asciidoctor-pdf --no-document
          gem install rouge
          # Valgfritt: diagrammer
          # gem install asciidoctor-diagram
          # Valgfritt: bred fontstøtte (Noto + emoji)
          sudo apt-get update
          sudo apt-get install -y fonts-noto fonts-noto-cjk fonts-noto-color-emoji

      - name: Build AsciiDoc to PDF
        run: asciidoctor-pdf book.adoc -o Practical-DDD-in-Kotlin.pdf

      - name: Upload PDF as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: book-pdf
          path: Practical-DDD-in-Kotlin.pdf
